### ISSUE TITLE
Portable version does not work

### ISSUE THREAD

**Issue by Natalia-Oreiro** [portapps/hlsw-portable#33]
Hi,

If a previous HLSW application has been installed or running on your computer, the portable version takes settings from the registers.

PS: I recommend moving to the latest HLSW build:

https://bayfiles.com/n8A52fwexf/hlsw_1_4_0_5_setup_exe
https://pastebin.com/raw/ZZTetKcR

Maybe use fix: https://github.com/dgibbs64/HLSW-Fixes

**Comment by crazy-max** [comment]
> If a previous HLSW application has been installed or running on your computer, the portable version takes settings from the registers.

That's the expected behavior: https://portapps.io/app/hlsw-portable/#modifications
