### ISSUE TITLE
Application start interrupted

### ISSUE THREAD

**Issue by m5m5k** [portapps/hlsw-portable#5]
#### Steps to reproduce this issue

1. Run "hlsw-portable.exe"

#### Expected behaviour

> A GUI

#### Actual behaviour

> A smal window appears. Window-Title: "HLSW portable", 
   Message-Text: 
   "An error has occured.
    Command failed"
   There is also a red cross-icon to see and just an OK-Button to click.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 1.4.0.3-1 win32

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** : Version 1909 (Build 18363.476)
[hlsw-portable.log](https://github.com/portapps/hlsw-portable/files/3932798/hlsw-portable.log)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@m5m5k Microsoft Visual C++ 2008 Redistributable Setup is required. Download here: https://www.microsoft.com/en-us/download/details.aspx?id=29

**Comment by m5m5k** [comment]
Great, thank you very much for your help. Why don´t you publish this information on the Website?

 

Have a nice day & thanks again

 

Michael

 
 

Gesendet: Samstag, 07. Dezember 2019 um 17:54 Uhr
Von: "CrazyMax" <notifications@github.com>
An: portapps/hlsw-portable <hlsw-portable@noreply.github.com>
Cc: m5m5k <m5m5k@online.de>, Mention <mention@noreply.github.com>
Betreff: Re: [portapps/hlsw-portable] Application start interrupted (#5)


@m5m5k Microsoft Visual C++ 2008 Redistributable Setup is required. Download here: https://www.microsoft.com/en-us/download/details.aspx?id=29

**Comment by crazy-max** [comment]
@m5m5k Yes I have added a note about this here: https://portapps.io/app/hlsw-portable/#infos
